# Generated by Django 5.0.2 on 2024-02-08 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campagne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description_poste", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Candidat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("cv", models.FileField(upload_to="candidat_cv/")),
                ("adresse", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=15)),
                (
                    "campagne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidats",
                        to="campaign.campagne",
                    ),
                ),
            ],
        ),
    ]
