# Generated by Django 5.0.2 on 2024-02-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidat",
            name="cvs",
            field=models.FileField(default="", upload_to="candidat_cv/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidat",
            name="cv",
            field=models.TextField(),
        ),
    ]
