# Generated by Django 5.0.2 on 2024-02-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0002_candidat_cvs_alter_candidat_cv"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("saved_filename", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
        migrations.RemoveField(
            model_name="candidat",
            name="cvs",
        ),
        migrations.AlterField(
            model_name="candidat",
            name="cv",
            field=models.FileField(upload_to="candidat_cv/"),
        ),
    ]
