# Generated by Django 5.0.2 on 2024-02-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0003_uploadedfile_remove_candidat_cvs_alter_candidat_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidat",
            name="cv_data_url",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="candidat",
            name="cv_original_name",
            field=models.TextField(default=""),
        ),
    ]
