# Generated by Django 5.0.2 on 2024-02-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0005_alter_candidat_adresse_alter_candidat_cv_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidat",
            name="cv",
        ),
        migrations.AddField(
            model_name="candidat",
            name="cv_path",
            field=models.FileField(blank=True, upload_to="candidat_cv/"),
        ),
    ]
