# Generated by Django 5.0.2 on 2024-02-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0006_remove_candidat_cv_candidat_cv_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidat",
            name="cv_path",
            field=models.TextField(blank=True),
        ),
    ]
