# Generated by Django 5.0.2 on 2024-02-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0007_alter_candidat_cv_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campagne",
            name="description_poste",
        ),
        migrations.RemoveField(
            model_name="campagne",
            name="titre",
        ),
        migrations.AddField(
            model_name="campagne",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="campagne",
            name="intitule_poste",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="campagne",
            name="nom",
            field=models.CharField(default="", max_length=255),
        ),
    ]
