# Generated by Django 5.0.2 on 2024-02-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0010_competence_langue_campagne_has_awards_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campagne",
            name="has_awards",
        ),
        migrations.RemoveField(
            model_name="campagne",
            name="has_certifications",
        ),
        migrations.RemoveField(
            model_name="campagne",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="campagne",
            name="minimum_degree",
        ),
        migrations.RemoveField(
            model_name="campagne",
            name="minimum_number_of_experiences",
        ),
        migrations.RemoveField(
            model_name="campagne",
            name="minimum_number_of_languages",
        ),
        migrations.RemoveField(
            model_name="campagne",
            name="minimum_number_of_years_of_experience",
        ),
        migrations.RemoveField(
            model_name="campagne",
            name="skills",
        ),
    ]
