# Generated by Django 5.0.2 on 2024-02-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0010_remove_critere_campagne_delete_uploadedfile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campagne",
            name="description_poste",
            field=models.TextField(default=""),
        ),
    ]
