# Generated by Django 5.0.2 on 2024-02-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0011_campagne_description_poste"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campagne",
            name="description",
        ),
    ]
