# Generated by Django 5.0.2 on 2024-02-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0012_campagne_has_awards_campagne_has_certifications_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
