# Generated by Django 5.0.2 on 2024-03-01 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0014_campagne_files"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="campagne",
            name="files",
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name="collaborateur",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborateurs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
