# Generated by Django 5.0.2 on 2024-03-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0015_alter_campagne_files_alter_collaborateur_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborateur",
            name="role",
            field=models.CharField(default="", max_length=255),
        ),
    ]
