# Generated by Django 5.0.2 on 2024-03-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0016_collaborateur_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborateur",
            name="user_full_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
