# Generated by Django 5.0.2 on 2024-03-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0017_collaborateur_user_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborateur",
            name="statut_invitation",
            field=models.CharField(default="En attente", max_length=255),
        ),
    ]
