# Generated by Django 5.0.2 on 2024-03-03 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0018_collaborateur_statut_invitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campagne",
            name="has_awards",
        ),
        migrations.RemoveField(
            model_name="campagne",
            name="has_certifications",
        ),
        migrations.AddField(
            model_name="campagne",
            name="certifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="", max_length=255)),
                (
                    "invite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations_recues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations_envoyees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Collaborateur",
        ),
    ]
