# Generated by Django 5.0.2 on 2024-03-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0019_remove_campagne_has_awards_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campagne",
            name="degrees",
            field=models.TextField(blank=True, null=True),
        ),
    ]
