# Generated by Django 5.0.2 on 2024-03-04 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0020_campagne_degrees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campagne",
            name="minimum_degree",
        ),
    ]
