# Generated by Django 5.0.3 on 2024-04-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaboration",
            name="statut_invitation",
            field=models.CharField(
                choices=[
                    ("En attente", "EN_ATTENTE"),
                    ("Acceptée", "ACCEPTEE"),
                    ("Expirée", "EXPIREE"),
                ],
                default="En attente",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="role",
            field=models.CharField(
                choices=[("Lecture", "LECTURE"), ("Ecriture", "ECRITURE")],
                default="Lecture",
                max_length=255,
            ),
        ),
    ]
