# Generated by Django 5.0.3 on 2024-04-14 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0002_collaboration_statut_invitation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaboration",
            name="invite",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborations_recues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="statut_invitation",
            field=models.CharField(
                choices=[
                    ("Envoyée", "ENVOYE"),
                    ("Acceptée", "ACCEPTEE"),
                    ("Expirée", "EXPIREE"),
                ],
                default="Envoyée",
                max_length=255,
            ),
        ),
    ]
