# Generated by Django 5.0.3 on 2024-06-01 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0003_alter_collaboration_invite_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaboration",
            name="invite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborations_recues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
