# Generated by Django 5.0.3 on 2024-03-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campagne", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=255)),
                ("prenom", models.CharField(blank=True, max_length=255)),
                ("cv_path", models.TextField(blank=True)),
                ("adresse", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=15)),
                ("cv_data_url", models.TextField()),
                ("cv_original_name", models.TextField()),
                (
                    "campagne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidats",
                        to="campagne.campagne",
                    ),
                ),
            ],
        ),
    ]
