# Generated by Django 5.0.3 on 2024-03-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidat",
            name="cv_data_url",
        ),
        migrations.RemoveField(
            model_name="candidat",
            name="email",
        ),
        migrations.AlterField(
            model_name="candidat",
            name="prenom",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
