# Generated by Django 5.0.3 on 2024-03-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0002_remove_candidat_cv_data_url_remove_candidat_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidat",
            name="prenom",
            field=models.TextField(blank=True),
        ),
    ]
