# Generated by Django 5.0.3 on 2024-03-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0003_alter_candidat_prenom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidat",
            name="adresse",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="candidat",
            name="cv_original_name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="candidat",
            name="cv_path",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="candidat",
            name="prenom",
            field=models.CharField(blank=True),
        ),
    ]
