# Generated by Django 5.0.3 on 2024-03-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0004_alter_candidat_adresse_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidat",
            old_name="cv_path",
            new_name="fichier",
        ),
        migrations.RenameField(
            model_name="candidat",
            old_name="nom",
            new_name="nom_complet",
        ),
        migrations.AddField(
            model_name="candidat",
            name="email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="candidat",
            name="fichier_sauvegarde",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="candidat",
            name="matches",
            field=models.JSONField(default=None),
        ),
    ]
