# Generated by Django 5.0.3 on 2024-03-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0005_rename_cv_path_candidat_fichier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidat",
            name="telephone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
