# Generated by Django 5.0.3 on 2024-04-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidat", "0008_remove_candidat_adresse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidat",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidat",
            name="texte_pdf",
            field=models.TextField(default=""),
        ),
    ]
