# Generated by Django 5.0.3 on 2024-03-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
