# Generated by Django 5.0.3 on 2024-03-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nom",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="prenom",
            field=models.TextField(default=""),
        ),
    ]
