# Generated by Django 5.0.3 on 2024-03-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_nom_user_prenom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nom",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="prenom",
            field=models.CharField(max_length=255),
        ),
    ]
