# Generated by Django 5.0.3 on 2024-04-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_nom_alter_user_prenom"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nom_complet",
            field=models.CharField(default="", max_length=255),
        ),
    ]
