# Generated by Django 5.0.3 on 2024-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_user_nom_complet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nom_complet",
            field=models.CharField(
                default="<django.db.models.fields.CharField> <django.db.models.fields.CharField>",
                max_length=255,
            ),
        ),
    ]
