# Generated by Django 5.0.3 on 2024-03-25 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campagne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(default="", max_length=255)),
                ("description_poste", models.TextField(default="")),
                ("intitule_poste", models.CharField(default="", max_length=255)),
                ("minimum_number_of_languages", models.IntegerField(default=0)),
                ("minimum_number_of_experiences", models.IntegerField(default=0)),
                ("languages", models.TextField(blank=True, null=True)),
                ("degrees", models.TextField(blank=True, null=True)),
                ("certifications", models.TextField(blank=True, null=True)),
                ("skills", models.TextField(blank=True, null=True)),
                ("files", models.JSONField(default=None)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campagnes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
