# Generated by Django 5.0.3 on 2024-06-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campagne", "0002_alter_campagne_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="campagne",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
